- name: install web component nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.debug.yum:
      name: nginx
      state: installed
    ansible.builtin.services:
      name: service enabled
      enable: yes
      start: yes
    ansible.builtin.uri:
  - name: Delete content & directory
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory 

  - name: Download file
    ansible.builtin.get_url:
      url: curl -o /tmp/web.zip https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy into roboshop.conf
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: restart the web
    ansible.builtin.service:
      name: nginx
      state: restarted
      